# Generated by Django 4.2.3 on 2023-07-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(default='asd', max_length=15),
            preserve_default=False,
        ),
    ]
