# Generated by Django 4.2.3 on 2023-07-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
