# Generated by Django 4.2.4 on 2023-08-16 06:20

import django.core.validators
from django.db import migrations, models
import final_exam.web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[final_exam.web.models.validate_name_contains_only_letters])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4)])),
                ('email', models.EmailField(max_length=45)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5), final_exam.web.models.password_contains_at_least_one_digit])),
            ],
        ),
    ]
