# Generated by Django 4.2.4 on 2023-08-16 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('category', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('event_image', models.URLField()),
            ],
        ),
    ]
