# Generated by Django 4.2.4 on 2023-08-16 08:10

from django.db import migrations, models
import final_exam.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_eventmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Festivals', 'Festivals'), ('Conferences', 'Conferences'), ('Performing Art', 'Performing Art'), ('Concerts', 'Concerts'), ('Theme Party', 'Theme Party'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='date',
            field=models.DateField(validators=[final_exam.web.models.validate_date_not_in_past]),
        ),
    ]
