# Generated by Django 4.2.1 on 2023-05-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_nullblankdemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_full_time',
            field=models.BooleanField(null=True),
        ),
    ]
