# Generated by Django 4.2.4 on 2023-08-15 00:13

import django.core.validators
from django.db import migrations, models
import exam_june_2023.web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), exam_june_2023.web.models.first_char_must_be_letter])),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1), exam_june_2023.web.models.first_char_must_be_letter])),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1)])),
                ('image_url', models.URLField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, default=18, null=True)),
            ],
        ),
    ]
